//! Extension point for the SaaS control plane.
//!
//! The engine is policy-free: it proxies S3 requests through the Wasm
//! pipeline and authenticates via API keys. Authorization (rate limits,
//! quotas, billing) and usage metering are injected through [`ControlPlane`].
//! The OSS self-host binary uses [`NoopControlPlane`]; the hosted SaaS
//! implements this trait to add workspaces, metering, and billing.

use async_trait::async_trait;
use uuid::Uuid;

use crate::workspace_storage::WorkspaceId;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AuthenticatedRequestContext {
    pub user_id: String,
    pub workspace_id: WorkspaceId,
}

/// Kind of S3 operation, for metering and authorization.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RequestKind {
    Write,
    Read,
}

/// Canonical S3 route that produced a usage receipt.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum UsageRoute {
    PutObject,
    GetObject,
    HeadObject,
    ListObjects,
    DeleteObject,
    AbortMultipartUpload,
    CompleteMultipartUpload,
}

/// Durable, idempotent usage receipt submitted after a billable operation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct UsageEvent {
    /// Receipt idempotency key generated by the gateway.
    pub id: Uuid,
    /// Canonical server-derived parent operation identity.
    pub operation_id: Uuid,
    pub bucket: String,
    pub kind: RequestKind,
    pub route: UsageRoute,
    pub source_bytes: u64,
    pub output_bytes: u64,
    pub processed_bytes: u64,
}

impl UsageEvent {
    pub fn new(
        id: Uuid,
        operation_id: Uuid,
        bucket: impl Into<String>,
        kind: RequestKind,
        route: UsageRoute,
        source_bytes: u64,
        output_bytes: u64,
    ) -> Self {
        Self {
            id,
            operation_id,
            bucket: bucket.into(),
            kind,
            route,
            source_bytes,
            output_bytes,
            processed_bytes: source_bytes.max(output_bytes),
        }
    }
}

/// Stable control-plane outcomes that the data plane can safely map to S3.
#[derive(Clone, Copy, Debug, Eq, PartialEq, thiserror::Error)]
pub enum MeteringError {
    #[error("usage metering is unavailable")]
    Unavailable,
    #[error("usage event conflicts with an existing receipt")]
    IdempotencyConflict,
    #[error("usage event was rejected")]
    Rejected,
}

/// Stable authorization dependency failures that the data plane can safely map to S3.
#[derive(Clone, Copy, Debug, Eq, PartialEq, thiserror::Error)]
pub enum AuthorizationError {
    #[error("authorization is unavailable")]
    Unavailable,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord)]
pub enum StreamingWriteMode {
    #[default]
    Off,
    Single,
    All,
}

/// Why a request was blocked. `code` is S3-style, `message` is human-readable.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BlockReason {
    pub code: &'static str,
    pub message: &'static str,
}

impl BlockReason {
    pub fn new(code: &'static str, message: &'static str) -> Self {
        Self { code, message }
    }
}

/// SaaS control-plane seam. The engine calls [`ControlPlane::authorize`]
/// before running the pipeline and [`ControlPlane::record`] after a
/// successful operation.
#[async_trait]
pub trait ControlPlane: Send + Sync + 'static {
    /// Authorize an authenticated user/workspace context. Return a block reason
    /// for a policy rejection, `None` to allow, or an error when authorization
    /// cannot make a decision.
    async fn authorize(
        &self,
        context: &AuthenticatedRequestContext,
        kind: RequestKind,
    ) -> Result<Option<BlockReason>, AuthorizationError>;

    /// Durably record usage after a successful operation. The gateway supplies
    /// canonical route and byte counts, with `processed_bytes` equal to
    /// `max(source_bytes, output_bytes)`; HEAD, LIST, and DELETE report zeroes.
    /// Implementations must treat an exact replay of `event.id` as success and
    /// reject conflicting reuse with [`MeteringError::IdempotencyConflict`].
    async fn record(
        &self,
        context: &AuthenticatedRequestContext,
        event: &UsageEvent,
    ) -> Result<(), MeteringError>;

    /// Optional tenant ceiling. `None` inherits the deployment ceiling; a
    /// tenant can only lower, never raise, the configured mode.
    async fn streaming_write_mode(
        &self,
        _context: &AuthenticatedRequestContext,
    ) -> Option<StreamingWriteMode> {
        None
    }
}

/// No-op control plane for the OSS self-host binary: authorizes everything,
/// records nothing.
#[derive(Debug, Default, Clone)]
pub struct NoopControlPlane;

#[async_trait]
impl ControlPlane for NoopControlPlane {
    async fn authorize(
        &self,
        _context: &AuthenticatedRequestContext,
        _kind: RequestKind,
    ) -> Result<Option<BlockReason>, AuthorizationError> {
        Ok(None)
    }

    async fn record(
        &self,
        _context: &AuthenticatedRequestContext,
        _event: &UsageEvent,
    ) -> Result<(), MeteringError> {
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn noop_authorizes_everything() {
        let cp = NoopControlPlane;
        let context = AuthenticatedRequestContext {
            user_id: "any-user".to_string(),
            workspace_id: WorkspaceId::new("workspace").unwrap(),
        };
        assert_eq!(cp.authorize(&context, RequestKind::Write).await, Ok(None));
        assert_eq!(cp.authorize(&context, RequestKind::Read).await, Ok(None));
    }

    #[tokio::test]
    async fn noop_records_without_effect() {
        let cp = NoopControlPlane;
        let context = AuthenticatedRequestContext {
            user_id: "u".to_string(),
            workspace_id: WorkspaceId::new("workspace").unwrap(),
        };
        let event = UsageEvent::new(
            Uuid::now_v7(),
            Uuid::now_v7(),
            "bucket",
            RequestKind::Write,
            UsageRoute::PutObject,
            12345,
            67890,
        );
        assert_eq!(cp.record(&context, &event).await, Ok(()));
    }

    #[test]
    fn usage_event_computes_processed_bytes_from_canonical_counts() {
        let event = UsageEvent::new(
            Uuid::now_v7(),
            Uuid::now_v7(),
            "bucket",
            RequestKind::Write,
            UsageRoute::PutObject,
            12,
            34,
        );
        assert_eq!(event.processed_bytes, 34);
    }

    #[test]
    fn block_reason_is_constructible() {
        let r = BlockReason::new("PaymentRequired", "out of credit");
        assert_eq!(r.code, "PaymentRequired");
        assert_eq!(r.message, "out of credit");
    }
}
