# coding: utf-8

"""
    S4 Gateway API

    Zero-trust PII filtering S3 gateway. Manage API keys, proxy S3 requests through presigned URLs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from s4_client.api.objects_api import ObjectsApi


class TestObjectsApi(unittest.TestCase):
    """ObjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ObjectsApi()

    def tearDown(self) -> None:
        pass

    def test_list_objects(self) -> None:
        """Test case for list_objects

        List all objects in the store
        """
        pass


if __name__ == '__main__':
    unittest.main()
