# coding: utf-8

"""
    S4 Gateway API

    Zero-trust PII filtering S3 gateway. Manage API keys, proxy S3 requests through presigned URLs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from s4_client.api.keys_api import KeysApi


class TestKeysApi(unittest.TestCase):
    """KeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KeysApi()

    def tearDown(self) -> None:
        pass

    def test_create_key(self) -> None:
        """Test case for create_key

        Create a new API key
        """
        pass

    def test_delete_key(self) -> None:
        """Test case for delete_key

        Revoke an API key
        """
        pass

    def test_get_keys(self) -> None:
        """Test case for get_keys

        List API keys for the authenticated user
        """
        pass


if __name__ == '__main__':
    unittest.main()
