# coding: utf-8

# flake8: noqa

"""
    S4 Gateway API

    Pluggable processing gateway for S3-compatible storage. Manage plugins and API keys, proxy S3 requests through a Wasm plugin pipeline.

    The version of the OpenAPI document: 0.3.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "KeysApi",
    "ObjectsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ApiKeyResponse",
    "CreateKeyRequest",
    "DeleteKeyRequest",
    "ListKeyResponse",
    "ObjectResponse",
]

# import apis into sdk package
from s4_client.api.keys_api import KeysApi as KeysApi
from s4_client.api.objects_api import ObjectsApi as ObjectsApi

# import ApiClient
from s4_client.api_response import ApiResponse as ApiResponse
from s4_client.api_client import ApiClient as ApiClient
from s4_client.configuration import Configuration as Configuration
from s4_client.exceptions import OpenApiException as OpenApiException
from s4_client.exceptions import ApiTypeError as ApiTypeError
from s4_client.exceptions import ApiValueError as ApiValueError
from s4_client.exceptions import ApiKeyError as ApiKeyError
from s4_client.exceptions import ApiAttributeError as ApiAttributeError
from s4_client.exceptions import ApiException as ApiException

# import models into sdk package
from s4_client.models.api_key_response import ApiKeyResponse as ApiKeyResponse
from s4_client.models.create_key_request import CreateKeyRequest as CreateKeyRequest
from s4_client.models.delete_key_request import DeleteKeyRequest as DeleteKeyRequest
from s4_client.models.list_key_response import ListKeyResponse as ListKeyResponse
from s4_client.models.object_response import ObjectResponse as ObjectResponse
