/**
 * S4 Gateway API
 * Zero-trust PII filtering S3 gateway. Manage API keys, proxy S3 requests through presigned URLs.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DeleteKeyRequest {
    'keyId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "keyId",
            "baseName": "key_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeleteKeyRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
